name: create docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker image registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Save tag in environment variable
      id: tag
      run: echo "docker_tag=$(date -u +"%Y%m%dT%H%M%SZ")" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        no-cache: true
#        tags: ${{ steps.metadata.outputs.tags }}
        tags: ghcr.io/${{ github.repository }}:${{ env.docker_tag }}
        push: true

